### ISSUE TITLE
Fail to build / run on Ubuntu 20.04

### ISSUE THREAD

**Issue by 0x804d8000** [Tencent/flare#18]
- An undefined reference to `pthread_once` (even if we've already link against `pthread`);
- `link_all_symbols` does not work correctly with shared linking.

**Comment by 0x804d8000** [comment]
cc @chen3feng

**Comment by 0x804d8000** [comment]
I think the root cause are the same. 

The first issue is seemingly related to [a weak symbol trick in libstdc++](https://stackoverflow.com/questions/27257655/undefined-reference-to-gthrw-pthread-key-createunsigned-int-void-voi). This undefined reference, IMHO, is not expected, but we can workaround it by forcing linking against `pthread` (`-Wl,--no-as-needed -lpthread -Wl,--as-needed`).

The second one should be a defect in blade. It should have used `--no-as-needed` when linking against targets marked as `link_all_symbols`.

I can fix the first one by specifying `linkflags` in `BLADE_ROOT` as `-Wl,--no-as-needed -lpthread -Wl,--as-needed`.

@chen3feng Do you mind taking a look as the second issue?

**Comment by 0x804d8000** [comment]
See chen3feng/blade-build#912.

**Comment by 0x804d8000** [comment]
Partly resolved by #9

**Comment by 0x804d8000** [comment]
Besides, LD_LIBRARY_PATH doesn’t seem to be working on Ubuntu 20.04. See #22 .

**Comment by 0x804d8000** [comment]
#26 should have fixed issues with `link_all_symbols`, I think.

**Comment by 0x804d8000** [comment]
Fixed by #34 .
